# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
  use_frameworks!

target 'PhotoFeeds' do

  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '10.0'
  inhibit_all_warnings!
  
  pod 'ImageSlideshow'
  pod 'ObjectMapper'
  pod 'Alamofire','4.8.2'
  pod 'SDWebImage'
  pod 'SVProgressHUD'
  

  target 'PhotoFeedsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PhotoFeedsUITests' do
    # Pods for testing
  end

end
